In [78]:
# Hogwart's sorting hat 
houses = ["Griffindor", "Slytherin", "hufflepuff", "Ravenclaw"]

q1_ans = input("Are you brave? (Y/N)")
if q1_ans == "Y":
  print(houses[0])
else:
  q2_ans = input("Are you ambitious? (Y/N)")
  if q2_ans == "Y":
    print(houses[1])
  else:
    q3_ans = input("Are you loyal? (Y/N)")
    if q3_ans == "Y":
      print(houses[2])
    else:
      q4_ans = input("Are you wise? (Y/N)")
      if q4_ans == "Y":
        print(houses[3])
      else:
        print("I cannot decide.")
        

Are you brave? (Y/N)Y
Griffindor


In [82]:
# Calculation of mean and std
import numpy as np

class statlist:
  def __init__(self, userlist):
    self.value = userlist

  def mean(self):
    return(np.mean(self.value))

  def sd(self):
    return(np.std(self.value))

  def print(self):
    print(self.value)

mydata = statlist(np.random.uniform(0,1,5))
mydata.print()
[mydata.mean(), mydata.sd()]

[0.0185762  0.07002214 0.48634511 0.60632946 0.56885144]


[0.35002487111469505, 0.2531482033831578]

In [83]:
# Lagging function
def lag(x, y):
  list_nan = np.array([np.nan]*y)
  list_input = np.delete(np.array(x), range(-y,0))
  list_lagged = np.append(list_nan, list_input)
  return list_lagged

a = [1, 2, 3, 5, 8]

lag(a,2)


array([nan, nan,  1.,  2.,  3.])

In [85]:
# lagGenerator

class laglist:
  def __init__(self, userlist):
    self.value = userlist

  def lagGenerator(self, lag):
    list_nan = np.array([np.nan]*lag)
    list_input = np.delete(np.array(self.value), range(-lag,0))
    return np.append(list_nan, list_input)

  def print(self):
    print(self.value)

mytest = laglist(np.random.uniform(0, 1, 5).tolist())

mytest.print()
mytest.lagGenerator(2)


[0.7453344309065021, 0.6692328934531846, 0.2649195576628094, 0.06633483442844157, 0.3700841979141063]


array([       nan,        nan, 0.74533443, 0.66923289, 0.26491956])